### PR TITLE
Add Toggle Option to Disable and Enable Naming LogiX Nodes

### PR DESCRIPTION
**Pull request by stiefeljackal**
# Main Feature
Added the ability to enable and disable the LogiX node renaming feature (also known as commenting). This is a feature request for those that want to open reference arrows only.

# Reop Chores
* Updated the Symlinked Libraries doc to state which libraries need to be symlinked. 
* Slightly changed the build script to include the NeosDir as an optional argument; the default value is still the same as in the previous build script.

### CODE REVIEW

**Comment by BlueCyro** [comment]
Thanks for the pull request, just as an FYI though I build all of my mods in VSCode, which is why there's no SLN and why I have a custom build script and such.

**Comment by stiefeljackal** [comment]
That's what I thought. I prefer VSCode over Visual Studio myself so it was nice to see that. :)

**Comment by BlueCyro** [comment]
I'll have to see about upgrading my build script and symlink folder with these suggestions. Still have yet to figure out a good workflow for making mods easily with VSCode without resorting to tons of powershell.

**Comment by stiefeljackal** [comment]
PowerShell is the way to go with this though when it comes to VSCode. If I think of something, I'll let you know. You can also reach out to me on Discord as well if you want to collaborate on something.

**Pull request merged**
